title: "To The Moon"
description: "A DeFi link list ..."

toc:
  enabled: false
  h_min: 2
  h_max: 6
  
# these categories are for page/file lists in the navigatin.html
category-list: [Strategies, Recipes, Other]

collections:
  pages:
    permalink: /:collection/:title:output_ext
    output: true  
    
theme: jekyll-theme-minimal

# Permalinks
# permalink: /:categories/:name:output_ext

exclude:
  - _drafts

plugins:
  - jekyll-toc



